### ISSUE TITLE
complete challenge 3

### ISSUE THREAD

**Issue by gugalnikov** [sysco-middleware/ansible-dojo-day0-part1#11]
- Help Richard to get the right code into his branch (use apt to install tomcat9)
- Test and polish code (needs to be similar to the rest of the challenges)
- Get the PR approved and merged into develop

**Comment by phamp890** [comment]
Richard has test and polish his code in his branch.
He has created a PR to develop.

**Comment by phamp890** [comment]
Richard fixed his code and merge to develop
