### ISSUE TITLE
Updating all playbooks to include apt update

### ISSUE THREAD

**Issue by gugalnikov** [sysco-middleware/ansible-dojo-day0-part1#12]
Ubuntu's apt-get catalog must be updated as the first (separate) task of the playbook
When executing this step, an error might show up due to a broken link in the catalog; you don't need to fix this, but you will need to ignore the error and continue for your playbook to run successfully (the catalog will be updated in spite of the error)

**Comment by dhayanands** [comment]
all playbooks have been updated to include apt update
